-- 初始化：启用 pgvector 扩展。
--
-- 说明：knowledge_chunks 表由应用按当前 embedding 维度动态创建，
-- 以免与真实 OpenAI 向量（1536 维）或本地回退向量（384 维）产生维度冲突。
--
-- EXTENSION 是给数据库安装的扩展，可以给数据库添加一批新的函数、类型、操作符；
-- vector 是 pgvector 扩展提供的数据类型，用来在数据库里存向量（embedding）。
-- 向量的定义：一串固定长度的浮点数，比如 [0.12, -0.35, 0.88, ...]；
-- 文本经过 embedding 模型会被转成这样的数字数组，语义越相近的文本，向量距离越近。
--
-- 注意：本文件由 PostgreSQL 容器首次启动时执行，必须是合法 SQL——
-- PostgreSQL 不支持 `#` 注释，只支持 `--` 与 `/* */`。
CREATE EXTENSION IF NOT EXISTS vector;
